### ISSUE TITLE
The new manager is fireing every 200 ms an event

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1070]
Opening the manager and doing nothing is constantly firing every 200ms an event in the background. This creates an unnecceary background load and can drain the battery:
![grafik](https://user-images.githubusercontent.com/10218721/116814709-90391b00-ab5a-11eb-93e0-6dbd6fdaa487.png)

**Comment by peuter** [comment]
The is this qooxdoo internal resize check for inlined applications (like the manager is). ID does not do much that constantly checking is the DOM-Element the inline component is injected in has changes its sizes and fire a resize event in that case.
As I am not aware of another solution to get notified when a DOM element has changed its size, but I did not wrote this core Qx code and I am not going to rewrite it.

Please keep in mind that a timer that has a 200ms interval und just looks into the bounding box of a dom element does not create a high workload. Those Timers (which a basicaly javascript `timeouts` are throttled or suspended when the tab gets inactive or the device is sleeping). So the is not much battery drainage. When you have the visu opened and active this timer is the least thing you have to worry when it comes to battery usage.

So for me this is a request that is 1. not a real problem and 2. might take a huge workload to find another solution where you probably gain almost nothing. I will close this issue here, because if you want to solve this it has to be done in qooxoo not in the cometvisu. You can open an issue in the qooxdoo repository if you still think this is an issue that should be addressed.
