### ISSUE TITLE
0.12.0-RC1: error messages with `update`

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1116]
https://forum.timberwolf.io/viewtopic.php?f=37&t=3272&p=36955#p36925

> Leider erhalte ich dann folgende Fehlermeldung
> 
> ```
> _update@https://10.0.1.14/proxy/visutest/cv/package-4.js:1:2709
> update@https://10.0.1.14/proxy/visutest/cv/index.js:318:329903
> onUpdate/<@https://10.0.1.14/proxy/visutest/cv/index.js:39:352744
> onUpdate@https://10.0.1.14/proxy/visutest/cv/index.js:39:352719
> update/<@https://10.0.1.14/proxy/visutest/cv/index.js:39:352892
> update@https://10.0.1.14/proxy/visutest/cv/index.js:39:352846
> handleRead@https://10.0.1.14/proxy/visutest/cv/index.js:39:362924
> dispatchEvent/
> ```
>

**Comment by peuter** [comment]
I don't think that we should open issues when even the initial reporter is not able to reproduce this error.
The stacktrace does not help because `_update` is maybe the most used method name (in almost every widget that receives updates implements it).

If there is a way to re-produce it, please re-open.
