### ISSUE TITLE
0.12.0-RC5: XML Editor can't handle JSON transform for MQTT

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1196]
The MQTT:JSON transform is "dynamic", i.e. the attribute must be extended by additional characters to specify which part of a communicated JSON is relevant for the widget.
The current drop down list doesn't allow such an extension.
-> https://forum.timberwolf.io/viewtopic.php?p=37761#p37761

Also the transform values in the drop down appear to be unsorted, thus it can be hard to find the correct one.

Additional chance for improvement: filter the offered transforms by the used backend.

**Comment by peuter** [comment]
I don't think that it is a good idea to change the behavior for all transforms to please just a single one. It opens a new source of errors. I think that adding a new attribute for this kind of specials that allows free content is the better option. There are already special address attributes for mqtt, so another one wouldn't hurt. The content of this new attribute can be appended to the transform string during parsing, so nothing has to be changed in the transform implementation.

**Comment by peuter** [comment]
Actually fetching a single value out of a JSON is a pre-transform task because you might need to apply a transform for that value in addition to that. So I would remove the json-transform and add a new "pre-process"-attribute which can be filled with something like "json:a.b". Then you can still apply a transform for that address to e.g. convert a date or something like that.
