### ISSUE TITLE
0.12.0-RC6/devel: Bad config isn't robust

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#1229]
Steps to reproduce (at least with current devel version; RC6 itself not tested):

- Open config in XML edit
- Have a `infotrigger` and put an invalid number like `foo` in the `upvalue`
- press reload

Effects:
Error on the console (uncaught NaN)
Bad error on the screen: no config is shown, only an empty screen

**Comment by peuter** [comment]
Did you test this in the source-build? Because that is an assertion error, and those property assertions are switched off in the build-target. I can only reproduce this error in the source version. In the build version the config loads without an error.

**Comment by peuter** [comment]
Must be something else because this particular error does not occur in a release (or a `-t build` compiled version). Also that thread is about layout problems I don't see anything about an error in RC6 in there.

The other threads the user reports RC6 errors I think are not related to config errors because the whole UI looks broken there, looks like even CSS files are not loaded there.

**Comment by ChristianMayer** [comment]
I got distracted by the many posts. 
I guess https://forum.timberwolf.io/viewtopic.php?p=38221#p38221 could be caused by a similar effect. As least the screen looks identical.
(And RC5 to RC6 doesn't make a difference here)

**Comment by peuter** [comment]
The error in the console is triggered by a property check. See here for more information about those checks: https://qooxdoo.org/documentation/v7.0/#/core/defining_properties?id=checking-incoming-values

**Comment by peuter** [comment]
As already mentioned this is a "source-only" problem and will not happen in a release -> close
