### ISSUE TITLE
Design alaska broken

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#473]
The alaska and alaska_slim designs are currently broken:
![cv2](https://cloud.githubusercontent.com/assets/10218721/21963357/b59253f8-db39-11e6-83ab-b8df822bfe27.jpg)

**Comment by peuter** [comment]
Well the underlying problem here is the hardcoded `height: 100%` here:
https://github.com/CometVisu/CometVisu/blob/develop/src/structure/pure/Page.js#L125

The error gets visible in this design because it sets a border around the `page > .clearfix` element. 
So a fix would be to remove the 100% but I guess its there for a reason and might break other things.

**Comment by ChristianMayer** [comment]
Hardcoded CSS in `style` attributes is always a bad idea, so we should fix that after the next release. For this release I also think it's too dangerous
