### ISSUE TITLE
Switching pages from left navbar causes redraw errors

### ISSUE THREAD

**Issue by joltcoke** [CometVisu/CometVisu#589]
If i'm selecting a new page from the left navbar, the old one remains active in the background. The new page is rendered on top. Selecting a new page from the top navbar doesn't show this behaviour.

I'm only able to reproduce the issue with Chrome. Safari works fine.

**Comment by peuter** [comment]
The contained metal-demo-config has a left navbar with pagejumps in it. Can you reproduce the error with that config? I can't. Otherwise an example config would help

**Comment by joltcoke** [comment]
No it's not reproducible with the metal demo. However I noticed, that the top navBar will loose the selection if you click on one of the page jumps on the leftNavBar. So the config structure is different to mine.

You can use the config I sent you for the reload issue to reproduce the problem.

**Comment by peuter** [comment]
Well the log you send me, is not "complete" because of the reload error. The included config parts, where most of you rooms seem to be defined in are not part of the log, because the error stopped processing the config vefore they got loaded.

I tried to click every pagejump in the configs left navbar and the few that worked showed no error. So lets hope it got fixed by one of the other fixes ;-) You can re-test this issue once #590, #592, and #593 git merged. If it still occurs a new log file might help.

**Comment by joltcoke** [comment]
With latest snapshot I can no longer reproduce the issue. Closing it for now... thanks!
