### ISSUE TITLE
Fix / enhance docu

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#798]
- [x] add files to toc that aren't included yet
- [x] fix warnings during generation
- [x] fix errors during generation

**Comment by peuter** [comment]
Ok found the toctree warnings and will have a look at them.

**Comment by peuter** [comment]
PR #812 should fix task 1 + 3

**Comment by ChristianMayer** [comment]
There are still a few `WARNING: Bullet list ends without a blank line; unexpected unindent.` where I can't find the source of the problem. The first three are actually
```
/mnt/timberwolf/var/www/html/git/doc/manual/de/colab/doc/directives.rst:204: WARNING: Bullet list ends without a blank line; unexpected unindent.
/mnt/timberwolf/var/www/html/git/doc/manual/de/colab/doc/directives.rst:405: WARNING: Bullet list ends without a blank line; unexpected unindent.
/mnt/timberwolf/var/www/html/git/doc/manual/de/colab/doc/directives.rst:405: WARNING: Bullet list ends without a blank line; unexpected unindent.
```
but the file doc/manual/de/colab/doc/directives.rst has only 230 lines...

So I guess it must happen somewhere internally during file mangling where the intermediate step is "broken" but not shown.

I could try to fix the RST files - but when I can't see the source I can't develop a fix

**Comment by peuter** [comment]
Thats exactly the problem: I also don't know, what and where the real problem is.

**Comment by ChristianMayer** [comment]
Would it be possible to store the (temporary) final file that sphinx should use somewhere?

**Comment by peuter** [comment]
No, I don't think that there is a way to export those intermediate files. But it's been 2,5 years since I wrote that code, so I might be wrong.

The problem is causes by the bullet lists used to show the XML-Schema element structure, like:

switch
* label
  * icon

The code that generates them is here: https://github.com/CometVisu/CometVisu/blob/develop/utils/docutils/directives/common.py#L211-L255
(take a look at `element_title`). But I never found a working alternative to correctly indent the elements to show the structure without using bullet lists. They generate warnings but do what they should do.

**Comment by ChristianMayer** [comment]
Well, that's solvable :)

**Comment by peuter** [comment]
Much better, but there are still some warnings left: 20 Warnings in DE and 68 in EN. Running local with force parameter `./cv doc -f` to make sure that everything is re-generated not just the changed stuff.

**Comment by ChristianMayer** [comment]
State is much better now -> move to 0.10.x
