### ISSUE TITLE
Demo mode enhancements

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#817]
Out of the review of #794: 
- [x] Temperatures should be different between the rooms
- [x] All rooms should exists (Büro/Kinder/Flur)
- [x] Slider doesn't slide by mouse (Chrome), similar to the tablet issue
- [x] pressed/unpressed button state looks too similar. The difference isn't easily visible
- [x] Wohnen: Licht vs. Licht mit Icons - it would be better to show what's possible in a "show off demo" than to educate about subtle differences
- [x] Refresh doesn't make sense in such a demo
- [x] Make demo more interactive, i.e. let switches switch something somewhere else to give better feedback (e.g. ColorChooser -> r+g+b slider; main light slider -> measured brightness in Lux; ...)

Mode possibilities (requiring deeper code changes):
- [x] Add time dimension (+ infinite loop) to testmode data json so that something is happening
- [x] Add "callback functions" to testmode data which can react to sent data by sending something else back. This could allow an interactive, simulated dim or shade. Even complex behavior like room temperature could be simulated then

**Comment by peuter** [comment]
I will open an extra issue for task 3, because I think it is a bug that does not only affect the demo mode (but I need to check that first). Task 4 is a design decision, which is also not part of the demo mode, thats how the metal design visualizes buttons since years I think and I'm fine with that.

All other tasks should be somehow handled in the new PR.

**Comment by ChristianMayer** [comment]
It's solved
