### ISSUE TITLE
Openweathermap Plugin breaks demo

### ISSUE THREAD

**Issue by ChristianMayer** [CometVisu/CometVisu#904]
https://www.cometvisu.org/CometVisu/de/latest/demo-source/source/ or https://www.cometvisu.org/CometVisu/de/latest/demo/ breaks with an exception as there's some bad handling of the mockup of the openweathermap response.
See also https://sentry.io/share/issue/79e8a9869e7b435abc0cd506ef829650/

But also opening `demo_testmode` locally fails, in this case due to a 401 with `{"cod":401, "message": "Invalid API key. Please see http://openweathermap.org/faq#error401 for more info."}`.

**Comment by peuter** [comment]
The failure on opening the demo locally is correct, because be default there is no fake data and it tries ti connect to the openweather api with the fake-id.

If you want to test the demo localy you have to build it with:
`./generate.py source --macro=CV_TESTMODE:resource/demo/media/demo_testmode_data.json`

Please note that you have to run `./generate.py source` again to disable the fake XHR handling.
